help/controllers/DefaultController.php
<?php

namespace help\controllers;

use Yii;

class DefaultController extends \yii\gii\controllers\DefaultController
{
    public function actionView($id)
    {
        $generator = $this->loadGenerator($id);
        $params = ['generator' => $generator, 'id' => $id];

        $preview = Yii::$app->request->post('preview');
        $generate = Yii::$app->request->post('generate');
        $answers = Yii::$app->request->post('answers');

        if ($preview !== null || $generate !== null) {
            if ($generator->validate()) {
                $generator->saveStickyAttributes();
                $files = $generator->generate();
                if ($generate !== null && !empty($answers)) {
                    $params['hasError'] = !$generator->save($files, (array)$answers, $results);
                    $params['results'] = $results;
                } else {
                    $params['files'] = $files;
                    $params['answers'] = $answers;
                }
            }
        }
        if (Yii::$app->request->isPost) {
            switch ($id) {
                case 'model':
                    $Generator = Yii::$app->request->getBodyParam('Generator');
                    if ($Generator['tableName'] && empty($Generator['modelClass'])){
                        $tableName =  $Generator['tableName'];
                        $TablePrefix = $generator->getTablePrefix();
                        $tableName = str_replace($TablePrefix, '', $tableName);
                        $tableNameArray = explode('_', $tableName);
                        $modelClass = '';
                        foreach ($tableNameArray as $item) {
                            $modelClass .= ucwords($item);
                        }
                        return $modelClass;
                    }

                    break;
            }

        }
        return $this->render('view', $params);
    }
}

help/controllers/SiteController.php
<?php

namespace help\controllers;


use yii\gii\controllers\DefaultController;
use yii\web\Response;

class SiteController extends DefaultController
{
    /**
     * Displays homepage.
     *
     * @return Response|string
     */
    public function actionIndex(): Response|string
    {
       return $this->redirect(['/gii']);
    }


}

help/views/gii/default/diff.php
<?php

/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 20:16:13
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2021-03-25 00:45:32
 */

/* @var $this yii\web\View */
/* @var $diff mixed */
?>
<div class="default-diff">
    <?php if ($diff === false): ?>
        <div class="alert alert-danger">此文件类型不支持差异.</div>
    <?php elseif (empty($diff)): ?>
        <div class="alert alert-success">Identical.</div>
    <?php else: ?>
        <div class="content"><?= $diff ?></div>
    <?php endif; ?>
</div>

help/views/gii/default/index.php
<?php

/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 18:19:29
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2022-05-26 18:26:14
 */

 
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $generators \yii\gii\Generator[] */
/* @var $content string */

$generators = Yii::$app->controller->module->generators;
$this->title = '开发者助手';
?>
<div class="default-index">
    <h1 class="border-bottom pb-3 mb-3">店滴云CMS <small class="text-muted">诚邀优秀php开发者</small></h1>

    <p class="lead mb-5">免费的多商户业务引擎</p>

    <div class="row">
        <?php foreach ($generators as $id => $generator): ?>
        <div class="generator col-lg-4">
            <h3><?= Html::encode($generator->getName()) ?></h3>
            <p style="min-height: 50px;"><?= $generator->getDescription() ?></p>
            <p><?= Html::a('创建代码', ['default/view', 'id' => $id], ['class' => ['btn', 'btn-outline-secondary']]) ?></p>
        </div>
        <?php endforeach; ?>
    </div>

    <p><a class="btn btn-success" href="http://doc.hopesfire.com/">官方开发文档</a></p>

</div>

help/views/gii/default/view.php
<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 21:55:17
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2021-03-25 00:41:17
 */
 

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\gii\components\ActiveField;
use yii\gii\CodeFile;

/* @var $this yii\web\View */
/* @var $generator yii\gii\Generator */
/* @var $id string panel ID */
/* @var $form yii\widgets\ActiveForm */
/* @var $results string */
/* @var $hasError bool */
/* @var $files CodeFile[] */
/* @var $answers array */

$this->title = $generator->getName();
$templates = [];
foreach ($generator->templates as $name => $path) {
    $templates[$name] = "$name ($path)";
}
?>
<div class="firetech-main" >
        <h1><?= Html::encode($this->title) ?></h1>

        <p><?= $generator->getDescription() ?></p>

        <?php $form = ActiveForm::begin([
            'id' => "$id-generator",
            'successCssClass' => 'is-valid',
            'errorCssClass' => 'is-invalid',
            'validationStateOn' => ActiveForm::VALIDATION_STATE_ON_INPUT,
            'fieldConfig' => [
                'class' => ActiveField::className(),
                'hintOptions' => ['tag' => 'small', 'class' => 'form-text text-muted'],
                'errorOptions' => ['class' => 'invalid-feedback']
            ],
        ]); ?>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="form-fields">
                    <?= $this->renderFile($generator->formView(), [
                        'generator' => $generator,
                        'form' => $form,
                    ]) ?>
                    <?= $form->field($generator, 'template')
                        ->sticky()
                        ->hint('请选择应该使用哪组模板库生成代码。')
                        ->label('模板库')
                        ->dropDownList($templates) ?>
                    <div class="form-group">
                        <?= Html::submitButton('预览', ['name' => 'preview', 'class' => 'btn btn-primary']) ?>

                        <?php if (isset($files)): ?>
                            <?= Html::submitButton('生成', ['name' => 'generate', 'class' => 'btn btn-success']) ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <?php
            if (isset($results)) {
                echo $this->render('view/results', [
                    'generator' => $generator,
                    'results' => $results,
                    'hasError' => $hasError,
                ]);
            } elseif (isset($files)) {
                echo $this->render('view/files', [
                    'id' => $id,
                    'generator' => $generator,
                    'files' => $files,
                    'answers' => $answers,
                ]);
            }
            ?>
        <?php ActiveForm::end(); ?>
</div>
    

help/views/gii/default/view/files.php
<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 22:06:07
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2021-03-25 00:50:43
 */
 

use yii\gii\CodeFile;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $generator \yii\gii\Generator */
/* @var $files CodeFile[] */
/* @var $answers array */
/* @var $id string panel ID */

?>
<div class="default-view-files">
    <p>点击上面的<code>生成按钮</code> 生成下面选择的文件的按钮:</p>

    <div class="row form-group">
        
        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <input id="filter-input" class="form-control" placeholder="Type to filter">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right margin-top">
            <div id="action-toggle" class="btn-group btn-group-xs">
                <label class="btn btn-success active" title="Filter files that are created">
                    <input type="checkbox" value="<?= CodeFile::OP_CREATE ?>" checked> 创建
                </label>
                <label class="btn btn-outline-secondary active" title="Filter files that are unchanged.">
                    <input type="checkbox" value="<?= CodeFile::OP_SKIP ?>" checked> 没有变化
                </label>
                <label class="btn btn-warning active" title="Filter files that are overwritten">
                    <input type="checkbox" value="<?= CodeFile::OP_OVERWRITE ?>" checked> 覆盖
                </label>
            </div>
        </div>
    </div>

    <table class="table table-bordered table-striped table-sm">
        <thead>
            <tr>
                <th class="file">创建文件列表</th>
                <th class="action">操作</th>
                <?php
                $fileChangeExists = false;
                foreach ($files as $file) {
                    if ($file->operation !== CodeFile::OP_SKIP) {
                        $fileChangeExists = true;
                        echo '<th><input type="checkbox" id="check-all"></th>';
                        break;
                    }
                }
                ?>

            </tr>
        </thead>
        <tbody id="files-body">
            <?php foreach ($files as $file): ?>
                <?php
                if ($file->operation === CodeFile::OP_OVERWRITE) {
                    $trClass = 'table-warning';
                } elseif ($file->operation === CodeFile::OP_SKIP) {
                    $trClass = 'table-active';
                } elseif ($file->operation === CodeFile::OP_CREATE) {
                    $trClass = 'table-success';
                } else {
                    $trClass = '';
                }
                ?>
            <tr class="<?= "$file->operation $trClass" ?>">
                <td class="file">
                    <?= Html::a(Html::encode($file->getRelativePath()), ['preview', 'id' => $id, 'file' => $file->id], ['class' => 'preview-code', 'data-title' => $file->getRelativePath()]) ?>
                    <?php if ($file->operation === CodeFile::OP_OVERWRITE): ?>
                        <?= Html::a('diff', ['diff', 'id' => $id, 'file' => $file->id], ['class' => 'diff-code badge badge-warning', 'data-title' => $file->getRelativePath()]) ?>
                    <?php endif; ?>
                </td>
                <td class="action">
                    <?php
                    if ($file->operation === CodeFile::OP_SKIP) {
                        echo 'unchanged';
                    } else {
                        echo $file->operation;
                    }
                    ?>
                </td>
                <?php if ($fileChangeExists): ?>
                <td class="check">
                    <?php
                    if ($file->operation === CodeFile::OP_SKIP) {
                        echo '&nbsp;';
                    } else {
                        echo Html::checkBox("answers[{$file->id}]", isset($answers) ? isset($answers[$file->id]) : ($file->operation === CodeFile::OP_CREATE));
                    }
                    ?>
                </td>
                <?php endif; ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="modal fade" id="preview-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header" style="display: flex;">
                    <div class="btn-group btn-group-sm" role="group">
                        <a class="modal-previous btn btn-outline-secondary" href="#" title="Previous File (Left Arrow)">
                            <span class="icon"></span>
                        </a>
                        <a class="modal-next btn btn-outline-secondary" href="#" title="Next File (Right Arrow)">
                            <span class="icon"></span>
                        </a>
                        <a class="modal-refresh btn btn-outline-secondary" href="#" title="Refresh File (R)">
                            <span class="icon"></span>
                        </a>
                        <a class="modal-checkbox btn btn-outline-secondary" href="#" title="Check This File (Space)">
                            <span class="icon"></span>
                        </a>
                        &nbsp;
                    </div>
                    <h5 class="modal-title ml-2">Modal title</h5>
                    <span class="modal-copy-hint ml-auto"><kbd>CTRL</kbd>+<kbd>C</kbd> to copy</span>
                    <div id="clipboard-container"><textarea id="clipboard"></textarea></div>
                    <button type="button" class="close ml-0" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Please wait ...</p>
                </div>
            </div>
        </div>
    </div>
</div>

help/views/gii/default/view/results.php
<?php
/* @var $this yii\web\View */
/* @var $generator yii\gii\Generator */
/* @var $results string */
/* @var $hasError bool */
?>
<div class="default-view-results">
    <?php
    if ($hasError) {
        echo '<div class="alert alert-danger">There was something wrong when generating the code. Please check the following messages.</div>';
    } else {
        echo '<div class="alert alert-success">' . $generator->successMessage() . '</div>';
    }
    ?>
    <pre><?= nl2br($results) ?></pre>
</div>

help/views/gii/layouts/generator.php
<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2022-05-26 17:47:35
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2022-06-28 16:53:35
 */

use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $generators \yii\gii\Generator[] */
/* @var $activeGenerator \yii\gii\Generator */
/* @var $content string */

$generators = Yii::$app->controller->module->generators;
$activeGenerator = Yii::$app->controller->generator;
?>
<?php $this->beginContent('@admin/views/gii/layouts/main.php'); ?>
<div class="row">
    <div class="col-md-3 col-sm-4">
        <div class="list-group">
            <?php
            $classes = ['list-group-item', 'd-flex', 'justify-content-between', 'align-items-center'];
            foreach ($generators as $id => $generator) {
                $label = Html::tag('span', Html::encode($generator->getName())) . '<span class="icon"></span>';
                echo Html::a($label, ['default/view', 'id' => $id], [
                    'class' => $generator === $activeGenerator ? array_merge($classes, ['active']) : $classes,
                ]);
            }
            ?>
        </div>
    </div>
    <div class="col-md-9 col-sm-8">
        <?= $content ?>
    </div>
</div>
<?php $this->endContent(); ?>

help/views/gii/layouts/main.php
<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 20:41:47
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2022-06-28 16:52:09
 */

use yii\helpers\Html;
use yii\widgets\Menu;

/* @var $this \yii\web\View */
/* @var $content string */

$asset = yii\gii\GiiAsset::register($this);
?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none">
    <?php $this->registerCsrfMetaTags(); ?>
    <title><?= Html::encode($this->title); ?></title>
    <?php $this->head(); ?>
    <style>
        .bg-gii {
            background-color: none;
            border-bottom: 1px solid #343a40;
        }
        .nav-links{
            width: 80px;
            display: inline-flex;
            color: #313131;
    font-size: 16px;
        }
        .navbar{
            position: relative;
        }
    </style>
</head>
<body>
    <div class="page-container">
        <?php $this->beginBody(); ?>
        <nav class="navbar navbar-expand-md navbar-dark bg-gii">
            <div class="container">
                <?php echo Html::a(Html::img('https://www.dandicloud.com/static/logo.png', [
                    'height' => '50',
                ]), ['default/index'], [
                    'class' => ['navbar-brand'],
                ]); ?>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#gii-nav"
                        aria-controls="gii-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="gii-nav">
                    <?php
                        echo Menu::widget([
                            'options' => ['class' => ['navbar-nav', 'ml-auto']],
                            'activateItems' => true,
                            'itemOptions' => [
                                'class' => ['nav-item'],
                            ],
                            'linkTemplate' => '<a class="nav-links" href="{url}" target="_block">{label}</a>',
                            'items' => [
                                ['label' => '官方网站', 'url' => 'https://www.dandicloud.com/'],
                                ['label' => '开发手册', 'url' => 'https://doc.ddicms.com/'],
                                ['label' => '官方sdk', 'url' => 'https://ext.dcloud.net.cn/plugin?id=13579'],
                            ],
                    ]);
                    ?>
                </div>
            </div>
        </nav>
        <div class="container" style="margin-top: 20px;">
            <?= $content; ?>
        </div>
        <div class="footer-fix"></div>
    </div>
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

help/views/layouts/generator.php
<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2022-05-26 17:47:35
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2022-06-28 16:53:35
 */

use yii\helpers\Html;
use yii\web\View;

/* @var $this View */
/* @var $generators \yii\gii\Generator[] */
/* @var $activeGenerator \yii\gii\Generator */
/* @var $content string */

$generators = Yii::$app->controller->module->generators;
$activeGenerator = Yii::$app->controller->generator;
?>
<?php $this->beginContent('@admin/views/gii/layouts/main.php'); ?>
<div class="row">
    <div class="col-md-3 col-sm-4">
        <div class="list-group">
            <?php
            $classes = ['list-group-item', 'd-flex', 'justify-content-between', 'align-items-center'];
            foreach ($generators as $id => $generator) {
                $label = Html::tag('span', Html::encode($generator->getName())) . '<span class="icon"></span>';
                echo Html::a($label, ['default/view', 'id' => $id], [
                    'class' => $generator === $activeGenerator ? array_merge($classes, ['active']) : $classes,
                ]);
            }
            ?>
        </div>
    </div>
    <div class="col-md-9 col-sm-8">
        <?= $content ?>
    </div>
</div>
<?php $this->endContent(); ?>

help/views/layouts/main.php
<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 20:41:47
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2022-06-28 16:52:09
 */

use yii\helpers\Html;
use yii\web\View;
use yii\widgets\Menu;

/* @var $this View */
/* @var $content string */

//$asset = yii\gii\GiiAsset::register($this);
?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none">
    <?php $this->registerCsrfMetaTags(); ?>
    <title><?= Html::encode($this->title); ?></title>
    <?php $this->head(); ?>
    <style>
        .bg-gii {
            background-color: none;
            border-bottom: 1px solid #343a40;
        }
        .nav-links{
            width: 80px;
            display: inline-flex;
            color: #313131;
    font-size: 16px;
        }
        .navbar{
            position: relative;
        }
    </style>
</head>
<body>
    <div class="page-container">
        <?php $this->beginBody(); ?>
        <nav class="navbar navbar-expand-md navbar-dark bg-gii">
            <div class="container">
                <?php echo Html::a(Html::img('https://diandi-1255369109.cos.ap-nanjing.myqcloud.com/cms%2Flogo-dz.png?q-sign-algorithm=sha1&q-ak=AKIDCUzY7R8RngO4SHsZOaZ_gwfwTd0NYJWGAnZb3O-G7-mAxe7XY-G-xbqmgPoS5ZSR&q-sign-time=1656406318;1656409918&q-key-time=1656406318;1656409918&q-header-list=&q-url-param-list=&q-signature=3573d680b29090c5ca690ddf3251edc56784873b&x-cos-security-token=Hc5k50gLBn5VQumKCxqh9Fajy4parlcaca25f20b88281b821e4d7f686940cb7c5Ycb5x4ng5EtD-4hHwsSe9yc1FTBzLF8j5nF_Ekd826DNd98KiJPZnDCsMAzUZ_BSgMVH9RU1wzsfxVTx4MlWbFv2T48fsBWGth9oChohbLDqtAkD_ayXaeO3J_Yxw9Mcd6KGS8Cetm4s6ovz5POy-N4XJJfYcMLf2iMMVghT9kM_I3FzIfCNPeSDl4Kfz_O', [
                    'height' => '50',
                ]), ['default/index'], [
                    'class' => ['navbar-brand'],
                ]); ?>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#gii-nav"
                        aria-controls="gii-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="gii-nav">
                    <?php
                        echo Menu::widget([
                            'options' => ['class' => ['navbar-nav', 'ml-auto']],
                            'activateItems' => true,
                            'itemOptions' => [
                                'class' => ['nav-item'],
                            ],
                            'linkTemplate' => '<a class="nav-links" href="{url}" target="_block">{label}</a>',
                            'items' => [
                                ['label' => '官方网站', 'url' => 'https://www.dandicloud.com/'],
                                ['label' => '开发社区', 'url' => 'https://www.hopesfire.com/'],
                                ['label' => '开发手册', 'url' => 'https://doc.hopesfire.com/'],
                            ],
                    ]);
                    ?>
                </div>
            </div>
        </nav>
        <div class="container" style="margin-top: 20px;">
            <?= $content; ?>
        </div>
        <div class="footer-fix"></div>
    </div>
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

help/views/site/diff.php
<?php

/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 20:16:13
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2021-03-25 00:45:32
 */

/* @var $this yii\web\View */
/* @var $diff mixed */
?>
<div class="default-diff">
    <?php if ($diff === false): ?>
        <div class="alert alert-danger">此文件类型不支持差异.</div>
    <?php elseif (empty($diff)): ?>
        <div class="alert alert-success">Identical.</div>
    <?php else: ?>
        <div class="content"><?= $diff ?></div>
    <?php endif; ?>
</div>

help/views/site/index.php
<?php

/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 18:19:29
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2022-05-26 18:26:14
 */

 
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $generators \yii\gii\Generator[] */
/* @var $content string */

$generators = Yii::$app->controller->module->generators;
$this->title = '开发者助手';
?>
<div class="default-index">
    <h1 class="border-bottom pb-3 mb-3">店滴云CMS <small class="text-muted">诚邀优秀php开发者</small></h1>

    <p class="lead mb-5">免费的多商户业务引擎</p>

    <div class="row">
        <?php foreach ($generators as $id => $generator): ?>
        <div class="generator col-lg-4">
            <h3><?= Html::encode($generator->getName()) ?></h3>
            <p style="min-height: 50px;"><?= $generator->getDescription() ?></p>
            <p><?= Html::a('创建代码', ['default/view', 'id' => $id], ['class' => ['btn', 'btn-outline-secondary']]) ?></p>
        </div>
        <?php endforeach; ?>
    </div>

    <p><a class="btn btn-success" href="http://doc.hopesfire.com/">官方开发文档</a></p>

</div>

help/views/site/view.php
<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-20 21:55:17
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2021-03-25 00:41:17
 */
 

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\gii\components\ActiveField;
use yii\gii\CodeFile;

/* @var $this yii\web\View */
/* @var $generator yii\gii\Generator */
/* @var $id string panel ID */
/* @var $form yii\widgets\ActiveForm */
/* @var $results string */
/* @var $hasError bool */
/* @var $files CodeFile[] */
/* @var $answers array */

$this->title = $generator->getName();
$templates = [];
foreach ($generator->templates as $name => $path) {
    $templates[$name] = "$name ($path)";
}
?>
<div class="firetech-main" >
        <h1><?= Html::encode($this->title) ?></h1>

        <p><?= $generator->getDescription() ?></p>

        <?php $form = ActiveForm::begin([
            'id' => "$id-generator",
            'successCssClass' => 'is-valid',
            'errorCssClass' => 'is-invalid',
            'validationStateOn' => ActiveForm::VALIDATION_STATE_ON_INPUT,
            'fieldConfig' => [
                'class' => ActiveField::className(),
                'hintOptions' => ['tag' => 'small', 'class' => 'form-text text-muted'],
                'errorOptions' => ['class' => 'invalid-feedback']
            ],
        ]); ?>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="form-fields">
                    <?= $this->renderFile($generator->formView(), [
                        'generator' => $generator,
                        'form' => $form,
                    ]) ?>
                    <?= $form->field($generator, 'template')
                        ->sticky()
                        ->hint('请选择应该使用哪组模板库生成代码。')
                        ->label('模板库')
                        ->dropDownList($templates) ?>
                    <div class="form-group">
                        <?= Html::submitButton('预览', ['name' => 'preview', 'class' => 'btn btn-primary']) ?>

                        <?php if (isset($files)): ?>
                            <?= Html::submitButton('生成', ['name' => 'generate', 'class' => 'btn btn-success']) ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <?php
            if (isset($results)) {
                echo $this->render('view/results', [
                    'generator' => $generator,
                    'results' => $results,
                    'hasError' => $hasError,
                ]);
            } elseif (isset($files)) {
                echo $this->render('view/files', [
                    'id' => $id,
                    'generator' => $generator,
                    'files' => $files,
                    'answers' => $answers,
                ]);
            }
            ?>
        <?php ActiveForm::end(); ?>
</div>
    